import numpy as np

from biomass.estimation import convert_scale, initialize_search_param

from name2idx import parameters as C
from name2idx import species as V
from set_model import initial_values, param_values

class SearchParam(object):

    # parameters with index
    idx_params = [
        C.EGFR_prod,
        C.ErbB2_prod,
        C.ErbB3_prod,
        C.IGF1R_prod,
        C.Met_prod,
        C.EGER_lig_binding,
        C.EGF_kD,
        C.EGFR_BTC_binding,
        C.ErbB3_lig_binding,
        C.IGF1R_lig_binding,
        C.Met_lig_binding,
        C.EGFR_dimerize,
        C.EGER_BTC_dimerize,
        C.ErbB2_dimerize,
        C.ErbB3_dimerize,
        C.IGF1R_dimerize,
        C.EGFR_ErbB2_dimerize,
        C.EGFR_ErbB2_BTC_dimerize,
        C.EGFR_ErbB3_dimerize,
        C.EGFR_ErbB3_BTC_dimerize,
        C.EGFR_ErbB3_dimerize_noHRG,
        C.ErbB2_ErbB3_dimerize,
        C.Met_dimerize,
        C.Met_ErbB3_dimerize,
        C.Met_lig_ErbB3_dimerize,
        C.Met_EGFR_dimerize,
        C.Met_EGFR_BTC_dimerize,
        C.EGFR_basal_activation,
        C.ErbB3_basal_activation,
        C.IGF1R_basal_activation,
        C.EGFR_ErbB2_basal_act,
        C.EGFR_ErbB3_basal_act,
        C.ErbB3_ErbB2_basal_act,
        C.Met_ErbB3_basal_act,
        C.Met_basal_act,
        C.Met_EGFR_basal_act,
        C.pEGFR_degradation,
        C.pEGFR_phosphatase_binding,
        C.pEGFRi_dephosph,
        C.EGFR_basal_recycle,
        C.pErbB2_internalize,
        C.pErbB2i_phosphatase,
        C.pErbB2i_dephosph,
        C.pErbB2_degradation,
        C.ErbB2_recycle,
        C.pErbB3_internalize,
        C.pErbB3_degradation,
        C.pErbN3i_phosphatase,
        C.pErbB3i_dephosph,
        C.ErbB3_basal_recycle,
        C.pIGF1R_internalize,
        C.pIGF1R_degradation,
        C.pIGF1Ri_phosphatase,
        C.pIGF1Ri_dephosph,
        C.IGF1R_basal_recycle,
        C.pErbB12_internalize,
        C.pErbB12_degradation,
        C.pErbB12i_phosphatase,
        C.pErbB12i_dephosph,
        C.pErbB32_internalize,
        C.pErbB32_degradation,
        C.pErbB32i_phasphatase,
        C.pErbB32i_dephosph,
        C.pErbB13_internalize,
        C.pErbB13_degradation,
        C.pErbB12i_phosphatase,
        C.pErbB13i_dephosph,
        C.pMet_internalize,
        C.pMet_degradation,
        C.pMet_phosphatase,
        C.pMet_dephosph,
        C.Met_recycle,
        C.pMetErbB3_internalize,
        C.pMetErbB3_degradation,
        C.pMetErbB3i_phasphatase,
        C.pMetErbB3i_dephosph,
        C.pMetEGFR_internalize,
        C.pMetEGFR_degradation,
        C.pMetEGFRi_phosphatase,
        C.pMetEGFRi_dephosph,
        C.MEK_phosphorylation_pErbB12,
        C.feedback_pAKT,
        C.init_pAKT,
        C.feedback_pERK,
        C.MEK_phosphorylation_pErbB13,
        C.MEK_phosphorylation_pMetd,
        C.MEK_phosphorylation_pMetEGFR,
        C.MEK_phosphorylation_pIGF1R,
        C.MEK_phosphorylation_pMetErbB3,
        C.MEK_internIGF1R_effect,
        C.MEK_phosphorylation_pIGF1R,
        C.pMEK_dephosphorylation,
        C.ERK_phosphorylation_pMEK,
        C.pERK_dephosphorylation,
        C.AKT_activation_pEGFR,
        C.feedback_pERK_on_AKT,
        C.AKT_activation_pErbB12,
        C.feedback_pS6K1,
        C.AKT_activation_pErbB13,
        C.feedback_pERK_on_AKT,
        C.AKT_activation_pErbB32,
        C.AKT_activation_pMetEGFR,
        C.AKT_activation_pMetd,
        C.AKT_activation_pIGF1R,
        C.AKT_activation_pMetErbB3,
        C.AKT_internIGF1R_effect,
        C.pAKT_deactivation,
        C.S6K1_phosphorylation_pAKT,
        C.S6K1_phosphorylation_pERK,
        C.pS6K1_dephosphorylation,
        C.S6_phosphorylation_pS6K1,
        C.S6_phosphorylation_pERK,
        C.pS6_dephosphorylation,    
    ]
    # initial values
    idx_initials = [
        # V.(specie)
    ]